import re

def update_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()

    # Add imports
    if 'AuthComponents' not in content:
        import_str = "import { Input, Label, BottomGradient } from '../components/ui/AuthComponents';\n"
        content = content.replace("import { useSEO } from '../hooks/useSEO';", "import { useSEO } from '../hooks/useSEO';\n" + import_str)

    # Replace labels
    content = re.sub(r'<label htmlFor="([^"]+)" className="[^"]+">', r'<Label htmlFor="\1" className="mb-2 block">', content)
    content = content.replace('</label>', '</Label>')

    # The standard input replacements
    input_pattern = r'<input\s+id="([^"]+)"\s+name="([^"]+)"\s+type="([^"]+)"\s+autoComplete="([^"]+)"\s+required\s+value=\{([^\}]+)\}\s+onChange=\{([^\}]+)\}\s+className="[^"]+"\s+placeholder="([^"]+)"\s*/>'
    
    # We need to use re.sub with a replacement function
    def replace_input(match):
        id_val = match.group(1)
        name_val = match.group(2)
        type_val = match.group(3)
        autoComplete_val = match.group(4)
        value_val = match.group(5)
        onChange_val = match.group(6)
        placeholder_val = match.group(7)
        
        return f'<Input id="{id_val}" name="{name_val}" type="{type_val}" autoComplete="{autoComplete_val}" required value={{{value_val}}} onChange={{{onChange_val}}} placeholder="{placeholder_val}" />'

    content = re.sub(input_pattern, replace_input, content)
    
    # Also replace for forms without `autoComplete` or different ordering
    # We'll just manually replace the input tags for Login.tsx and Register.tsx using a simpler approach since the exact string matches what was generated by the previous script
    
    # Submit button
    # Just append `<BottomGradient />` before `</button>` for the submit button
    submit_button_end = '</button>'
    # we need to be careful to only add it to the main submit button.
    # The main submit button has `type="submit"`.
    # So let's find `type="submit"` and the following `</button>`
    
    if '<BottomGradient />' not in content:
        content = content.replace('</button>\n              </motion.div>\n\n              <motion.div', '<BottomGradient />\n                </button>\n              </motion.div>\n\n              <motion.div')

    with open(filepath, 'w') as f:
        f.write(content)

update_file('src/pages/Login.tsx')
update_file('src/pages/Register.tsx')
print("Updated files to use custom components")
